1558759935332	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558759994779	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558760000823	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558760137741	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558760143978	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558761314958	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558761314958	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558761314960	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558761315956	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558761315960	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558761315960	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558761315967	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558761315967	Sync.Service	INFO	Starting sync at 2019-05-24 23:15:15 in browser session fq4s4dI8VdD-
1558761315968	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558761315971	Sync.Status	INFO	Resetting Status.
1558761315971	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558761315987	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558761315987	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558761315988	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558761315988	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558761315989	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558761315993	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
