1558674552179	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558674681932	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558674687666	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558674857898	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558674863615	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558675213097	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558675213098	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558675213120	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558675214096	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558675218005	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558675218005	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558675218014	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558675218014	Sync.Service	INFO	Starting sync at 2019-05-23 23:20:18 in browser session Igju9bUWkDxV
1558675218014	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558675218019	Sync.Status	INFO	Resetting Status.
1558675218019	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558675218041	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558675218041	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558675218041	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558675218042	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558675218043	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558675218048	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
