1558750001706	Sync.LogManager	DEBUG	Flushing file log
1558750001730	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557886001730
1558750001835	Sync.LogManager	DEBUG	Done deleting files.
1558750002664	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558750004458	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558750010748	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558750317373	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558750317373	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558750317375	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558750318372	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558750319646	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558750319646	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558750319649	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558750319650	Sync.Service	INFO	Starting sync at 2019-05-24 20:11:59 in browser session C7qc6VPHag_Z
1558750319650	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558750319655	Sync.Status	INFO	Resetting Status.
1558750319655	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558750319672	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558750319672	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558750319672	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558750319673	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558750319673	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1558750319674	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 3756042 ms.
1558750319674	Sync.SyncScheduler	DEBUG	Next sync in 3756042 ms. (why=client-backoff-schedule)
1558750319677	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
