1558751199253	Sync.LogManager	DEBUG	Flushing file log
1558751199273	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557887199273
1558751199337	Sync.LogManager	DEBUG	Done deleting files.
1558751270340	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558751270341	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558751270346	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558751271340	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558751271567	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558751271567	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558751271573	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558751271573	Sync.Service	INFO	Starting sync at 2019-05-24 20:27:51 in browser session p3tpBcsAkZXJ
1558751271574	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558751271578	Sync.Status	INFO	Resetting Status.
1558751271578	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558751271595	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558751271596	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558751271596	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558751271597	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558751271597	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558751271600	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
