1558665898118	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1558666948925	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558666948925	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558666948928	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1558666949925	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558666952343	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558666952343	Sync.Service	INFO	Starting sync at 2019-05-23 21:02:32 in browser session EmC99OI5yL9m
1558666952344	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558666952348	Sync.Status	INFO	Resetting Status.
1558666952348	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558666952361	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558666952362	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558666952362	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558666952362	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558666952365	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558666952370	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
