1558579040893	Sync.LogManager	DEBUG	Flushing file log
1558579040913	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557715040913
1558579040928	Sync.LogManager	DEBUG	Done deleting files.
1558579041857	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558579043785	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558579049611	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558579356572	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558579356573	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558579356579	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558579357572	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558579358846	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558579358846	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558579358852	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558579358853	Sync.Service	INFO	Starting sync at 2019-05-22 20:42:38 in browser session feW6KSQ4L3zF
1558579358853	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558579358860	Sync.Status	INFO	Resetting Status.
1558579358860	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558579358875	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558579358876	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558579358876	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558579358876	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558579358877	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1558579358877	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 3579906 ms.
1558579358877	Sync.SyncScheduler	DEBUG	Next sync in 3579906 ms. (why=client-backoff-schedule)
1558579358882	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
